// This module contains the arctangent lookup table for the CORDIC algorithm.
// Generated by ../python/atan_lut.py

module atan_lut(output reg [19:0] atan_table [0:15]);
    initial begin
        atan_table[0] = 20'hC90FD; // atan(2^-0) * 2^20
        atan_table[1] = 20'h76B19; // atan(2^-1) * 2^20
        atan_table[2] = 20'h3EB6E; // atan(2^-2) * 2^20
        atan_table[3] = 20'h1FD5B; // atan(2^-3) * 2^20
        atan_table[4] = 20'h0FFAA; // atan(2^-4) * 2^20
        atan_table[5] = 20'h07FF5; // atan(2^-5) * 2^20
        atan_table[6] = 20'h03FFE; // atan(2^-6) * 2^20
        atan_table[7] = 20'h01FFF; // atan(2^-7) * 2^20
        atan_table[8] = 20'h00FFF; // atan(2^-8) * 2^20
        atan_table[9] = 20'h007FF; // atan(2^-9) * 2^20
        atan_table[10] = 20'h003FF; // atan(2^-10) * 2^20
        atan_table[11] = 20'h001FF; // atan(2^-11) * 2^20
        atan_table[12] = 20'h000FF; // atan(2^-12) * 2^20
        atan_table[13] = 20'h0007F; // atan(2^-13) * 2^20
        atan_table[14] = 20'h0003F; // atan(2^-14) * 2^20
        atan_table[15] = 20'h0001F; // atan(2^-15) * 2^20
    end
endmodule
